
INSERT INTO ideation_depositaire_types values
	(1, "PARTICULIER", "Particulier", "NONE"),
	(2, "AUTRE", "Autre", "FREE"),
	(3, "CONSEIL", "Conseil de quartier", "LIST"),
	(4, "ASSO", "Association", "FREE");
	
INSERT INTO ideation_depositaire_types_values values
    (1,"CONSEIL","01VENDO","1er - Vendôme"),
    (2,"CONSEIL","01PALAI","1er - Palais Royal"),
    (3,"CONSEIL","01LESHA","1er - Les Halles"),
    (4,"CONSEIL","01SAINT","1er - Saint-Germain l’Auxerrois"),
    (5,"CONSEIL","02VIVIE","2e - Vivienne – Gaillon"),
    (6,"CONSEIL","02SENTI","2e - Sentier"),
    (7,"CONSEIL","02MONTO","2e - Montorgeuil – Saint Denis"),
    (8,"CONSEIL","03ENFAN","3e - Enfants rouges"),
    (9,"CONSEIL","03ARTSE","3e - Arts-et-Métiers"),
    (10,"CONSEIL","03SAINT","3e - Sainte-Avoie"),
    (11,"CONSEIL","03ARCHI","3e - Archives"),
    (12,"CONSEIL","04ARSEN","4e - Arsenal"),
    (13,"CONSEIL","04SAING","4e - Saint-Gervais"),
    (14,"CONSEIL","04LESIL","4e - Les îles"),
    (15,"CONSEIL","04SAINM","4e - Saint-Merri"),
    (16,"CONSEIL","05SAINT","5e - Saint Victor"),
    (17,"CONSEIL","05SORBO","5e - Sorbonne"),
    (18,"CONSEIL","05VALDE","5e - Val de Grâce"),
    (19,"CONSEIL","05JARDI","5e - Jardin des Plantes"),
    (20,"CONSEIL","06MONNA","6e - Monnaie"),
    (21,"CONSEIL","06NOTRE","6e - Notre-Dame des Champs"),
    (22,"CONSEIL","06ODEO","6e - Odéon"),
    (23,"CONSEIL","06RENNE","6e - Rennes"),
    (24,"CONSEIL","06SAING","6e - Saint-Germain des Prés"),
    (25,"CONSEIL","06SAINP","6e - Saint-Placide"),
    (26,"CONSEIL","07GROSC","7e - Gros caillou"),
    (27,"CONSEIL","07ECOLE","7e - École militaire"),
    (28,"CONSEIL","07INVAL","7e - Invalides"),
    (29,"CONSEIL","07SAINT","7e - Saint-Thomas d’Aquin"),
    (30,"CONSEIL","08HOCHE","8e - Hoche Friedland"),
    (31,"CONSEIL","08MONCE","8e - Monceau"),
    (32,"CONSEIL","08MAIRI","8e - Mairie"),
    (33,"CONSEIL","08EUROP","8e - Europe"),
    (34,"CONSEIL","08ELYSE","8e - Elysée Madeleine"),
    (35,"CONSEIL","08TRIAN","8e - Triangle d’Or"),
    (36,"CONSEIL","08SAINT","8e - Saint-Philippe du Roule"),
    (37,"CONSEIL","09FAUBO","9e - Faubourg Montmartre"),
    (38,"CONSEIL","09BLANC","9e - Blanche - Trinité"),
    (39,"CONSEIL","09PIGAL","9e - Pigalle – Martyrs"),
    (40,"CONSEIL","09ANVER","9e - Anvers – Montholon"),
    (41,"CONSEIL","09OPERA","9e - Opéra – Chaussée d’Antin"),
    (42,"CONSEIL","10SAIN","10e - Saint-Vincent de Paul - Lariboisière"),
    (43,"CONSEIL","10LOUI","10e - Louis Blanc - Aqueduc"),
    (44,"CONSEIL","10GRAN","10e - Grange-aux-Belles - Terrage"),
    (45,"CONSEIL","10FAUB","10e - Faubourg du Temple - Hôpital Saint-Louis"),
    (46,"CONSEIL","10PORT","10e - Porte Saint-Denis - Paradis"),
    (47,"CONSEIL","10CHAT","10e - Château d'Eau - Lancry"),
    (48,"CONSEIL","11BELL","11e - Belleville Saint-Maur"),
    (49,"CONSEIL","11LEON","11e - Léon Blum Folie-Régnault"),
    (50,"CONSEIL","11NATI","11e - Nation Alexandre Dumas"),
    (51,"CONSEIL","11BAST","11e - Bastille Popincourt"),
    (52,"CONSEIL","11REPU","11e - République Saint-Ambroise"),
    (53,"CONSEIL","12JARD","12e - Jardin de Reuilly"),
    (54,"CONSEIL","12VALL","12e - Vallée de Fécamp"),
    (55,"CONSEIL","12ALIG","12e - Aligre – Gare de Lyon"),
    (56,"CONSEIL","12NATI","12e - Nation – Picpus"),
    (57,"CONSEIL","12BELN","12e - Bel Air Nord"),
    (58,"CONSEIL","12BELS","12e - Bel Air Sud"),
    (59,"CONSEIL","12BERC","12e - Bercy"),
    (60,"CONSEIL","13CROU","13e - Croulebarbe"),
    (61,"CONSEIL","13SALP","13e - Salpêtrière – Austerlitz"),
    (62,"CONSEIL","13BIBL","13e - Bibliothèque Dunois Jeanne d’Arc"),
    (63,"CONSEIL","13NATI","13e - Nationale Deux-moulins"),
    (64,"CONSEIL","13OLYM","13e - Olympiades Choisy"),
    (65,"CONSEIL","13PATA","13e - Patay Masséna"),
    (66,"CONSEIL","13BIEV","13e - Bièvres Sud Tolbiac"),
    (67,"CONSEIL","13BUTT","13e - Buttes-aux-cailles Daviel"),
    (68,"CONSEIL","14MONR","14e - Montparnasse - Raspail"),
    (69,"CONSEIL","14MOUR","14e - Mouton - Duvernet"),
    (70,"CONSEIL","14PERN","14e - Pernety"),
    (71,"CONSEIL","14MOND","14e - Montsouris – Dareau"),
    (72,"CONSEIL","14JEAN","14e - Jean Moulin – Porte d’Orléans"),
    (73,"CONSEIL","14DIDO","14e - Didot – Porte de Vanves"),
    (74,"CONSEIL","15ALLE","15e - Alleray / Procession"),
    (75,"CONSEIL","15CAMB","15e - Cambronne / Garibadli"),
    (76,"CONSEIL","15CITR","15e - Citroën / Boucicaut"),
    (77,"CONSEIL","15DUPL","15e - Dupleix / Motte-Picquet"),
    (78,"CONSEIL","15EMER","15e - Emeriau / Zola"),
    (79,"CONSEIL","15GEOR","15e - Georges Brassens"),
    (80,"CONSEIL","15PAST","15e - Pasteur / Montparnasse"),
    (81,"CONSEIL","15SAIN","15e - Saint-Lambert"),
    (82,"CONSEIL","15VAUG","15e - Vaugirard / Parc des Expositions"),
    (83,"CONSEIL","15VIOL","15e - Violet / Commerce"),
    (84,"CONSEIL","16AUTS","16e - Auteuil-Sud"),
    (85,"CONSEIL","16AUTN","16e - Auteuil-Nord"),
    (86,"CONSEIL","16MUES","16e - Muette-Sud"),
    (87,"CONSEIL","16MUEN","16e - Muette-Nord"),
    (88,"CONSEIL","16DAUP","16e - Dauphine"),
    (89,"CONSEIL","16CHAI","16e - Chaillot"),
    (90,"CONSEIL","17TERN","17e - Ternes-Maillot"),
    (91,"CONSEIL","17CHAM","17e - Champerret-Berthier"),
    (92,"CONSEIL","17COUR","17e - Courcelles-Wagram"),
    (93,"CONSEIL","17PERE","17e - Pereire-Malesherbes"),
    (94,"CONSEIL","17LEGE","17e - Legendre-Levis"),
    (95,"CONSEIL","17BATI","17e - Batignolles-Cardinet"),
    (96,"CONSEIL","17LAFO","17e - La Fourche-Guy Môquet"),
    (97,"CONSEIL","17EPIN","17e - Epinettes-Bessières"),
    (98,"CONSEIL","18CHAR","18e - Charles Hermite-Evangile"),
    (99,"CONSEIL","18LACH","18e - La Chapelle-Marx Dormoy"),
    (100,"CONSEIL","18GOUT","18e - Goutte d’Or-Château Rouge"),
    (101,"CONSEIL","18AMIR","18e - Amiraux-Simplon-Poissonniers"),
    (102,"CONSEIL","18MOSK","18e - Moskova-Porte de Montmartre-Porte de Clignancourt"),
    (103,"CONSEIL","18GRAN","18e - Grandes Carrières-Clichy"),
    (104,"CONSEIL","18CLIG","18e - Clignancourt-Jules Joffrin"),
    (105,"CONSEIL","18MONT","18e - Montmartre"),
    (106,"CONSEIL","19BASB","19e - Bas Belleville "),
    (107,"CONSEIL","19PLAT","19e - Plateau "),
    (108,"CONSEIL","19PLAC","19e - Place des Fêtes "),
    (109,"CONSEIL","19PORT","19e - Porte des Lilas"),
    (110,"CONSEIL","19DANU","19e - Danube "),
    (111,"CONSEIL","19BASS","19e - Bassin de la Villette"),
    (112,"CONSEIL","19MANI","19e - Manin Jaurès"),
    (113,"CONSEIL","19FLAN","19e - Flandre Aubervilliers"),
    (114,"CONSEIL","19SECR","19e - Secrétan"),
    (115,"CONSEIL","19PONT","19e - Pont de Flandre"),
    (116,"CONSEIL","19ROSA","19e - Rosa Parks – Macdonald"),
    (117,"CONSEIL","20AMAN","20e - Amandiers Ménilmontant"),
    (118,"CONSEIL","20BELL","20e - Belleville"),
    (119,"CONSEIL","20GAMB","20e - Gambetta"),
    (120,"CONSEIL","20PLAI","20e - Plaine Lagny"),
    (121,"CONSEIL","20REUN","20e - Réunion Père Lachaise"),
    (122,"CONSEIL","20SAIN","20e - Saint Blaise"),
    (123,"CONSEIL","20TELE","20e - Télégraphe Pelleport Saint Fargeau")
;

INSERT INTO ideation_campagnes values
	(1, "C", "Budget Participatif 2016", "Campagne du budget participatif Paris 2016", 1, "NONE", NULL );

INSERT INTO ideation_campagnes_depositaires values
	(1, "C", "PARTICULIER"),
	(2, "C", "CONSEIL"),
	(4, "C", "ASSO"),
	(5, "C", "AUTRE");

INSERT INTO ideation_campagnes_phases values
	(1, "VISIBILITY", "C", "2016-01-13 12:00:00", "2017-03-15 12:00:00"),
	(2, "IDEATION", "C", "2016-01-15 12:00:00", "2016-03-15 12:00:00");

INSERT INTO ideation_campagnes_themes values
	(1, "C", "CADRE", "Cadre de vie", "Description de cadre de vie.", 1, NULL),
	(2, "C", "CULTURE", "Culture et patrimoine", "Description de culture et patrimoine.", 1, NULL),
	(3, "C", "ECO" ,  "Economie et emploi", "description de  Economie et emploi", 1, NULL),
	(4, "C", "EDU",  "Education et jeunesse"  , "description de  Education et jeunesse", 1, NULL),
	(5, "C", "NAT",  "Nature en ville"  , "description de  Nature en ville", 1, NULL),
	(6, "C", "PROPRETE",  "Propreté"  , "description de propreté", 1, NULL),
	(7, "C", "SOLIDARITE",  "Solidarité"  , "description de solidarité", 1, NULL),
	(8, "C", "SPORT",  "Sport"  , "description de sport", 1, NULL),
	(9, "C", "TRANSPORT",  "Transport et mobilité"  , "description de Transport et mobilité", 1, NULL),
	(10, "C", "NUMERIQUE",  "Ville intelligente et numérique"  , "description de Ville intelligente et numérique", 1, NULL),
	(11, "C", "VIVREENSEMBLE",  "Vivre ensemble"  , "description de vivre ensemble", 1, NULL),
	(12, "C", "ENVIRONNEMENT",  "Environnement"  , "description de environnement", 1, NULL),
	(13, "C", "LOGEMENT",  "Logement et habitat"  , "description de logement et habitat", 1, NULL),
	(14, "C", "SECURITE",  "Prévention et sécurité"  , "description de prévention et sécurité", 1, NULL),
	(15, "C", "PARTICIPATION",  "Participation citoyenne"  , "description de participation citoyenne", 1, NULL);
